### ISSUE TITLE
Missing substatus field

### ISSUE THREAD

**Issue by kevbite** [HakanL/shippo-csharp-client#6]
We're currently using your fork of the shippo library due to requiring support for .NET5 and the official version only support .NET Framework.

However, the issue is the same and I've raised it here - https://github.com/goshippo/shippo-csharp-client/issues/61

Is there any chance you could get this merged in from someone else's fork or at least this single commit https://github.com/dochoffiday/shippo-csharp-client/commit/a00025f3b672ae216cdb1684ea70ecf91498f7da?

Thanks

**Comment by HakanL** [comment]
Thanks for opening a ticket for this. I have cherry-picked in that change and published a new NuGet package. Please verify that it will work for you.

**Comment by kevbite** [comment]
This is working great, Thanks for the speedy response @HakanL!
