### ISSUE TITLE
enum TrackingStatuses need support PRE_TRANSIT

### ISSUE THREAD

**Issue by lifeglam** [HakanL/shippo-csharp-client#7]
Will get error converting value "PRE_TRANSIT" to type 'Shippo.ShippoEnums+TrackingStatuses
From https://goshippo.com/docs/tracking/ enum TrackingStatuses need support PRE_TRANSIT

**Comment by HakanL** [comment]
It's already in there: https://github.com/HakanL/shippo-csharp-client/blob/master/Shippo/ShippoEnums.cs#L18

**Comment by lifeglam** [comment]
https://github.com/HakanL/shippo-csharp-client/blob/master/Shippo/Models/Transaction.cs#L34 was using another enum defined at 
https://github.com/HakanL/shippo-csharp-client/blob/master/Shippo/ShippoEnums.cs#L76 which does not have PRE_TRANSIT.

**Comment by HakanL** [comment]
Good catch, fix pushed and Nuget package 2.0.13 indexing.
